version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql-api-enriquecimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: "api_enriquecimento"
    ports:
      - '3306:3306'
    volumes:
      - './data/enriquecimento/backup:/var/lib/mysql'
      - './data/enriquecimento:/docker-entrypoint-initdb.d'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge