version: '3.9'

services:

  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql-api-enriquecimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: "api_enriquecimento"
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'